### ISSUE TITLE
Any Getting started doc?

### ISSUE THREAD

**Issue by jabrena** [thegreystone/jmc-flame-view#2]
Hi @thegreystone, 

any note to use the `flame view`?

Great idea

Cheers

Juan Antonio

**Comment by thegreystone** [comment]
I'll add some notes. :)

**Comment by thegreystone** [comment]
Added info in the readme. Note that I will fix the JSON generation to use actual real values on the plane home. Should be in on Sunday.

If there isn't enough information in the README, please let me know what else I should put in there.

**Comment by thegreystone** [comment]
Also, added link to a blog that should help:
http://hirt.se/blog/?p=989

:)

**Comment by jabrena** [comment]
Many thanks Marcus.

This week, I will test it.

Cheers
